---
- name: Setup API call creds
  set_fact:
    scormcloud_auth_composite:    "{{ scormcloud_api_key }}:{{ scormcloud_api_secret }}"
    #  no_log: true

- name: Setup API call creds
  set_fact:
    scormcloud_api_auth:          "{{ scormcloud_auth_composite | b64encode }}"
    #no_log: true

#- name: 'DEBUG: API call creds'
#  debug:
#    msg: "scormcloud_auth_composite is {{ scormcloud_auth_composite }}"
#
#- name: 'DEBUG: API call creds'
#  debug:
#    msg: "scormcloud_api_auth is {{ scormcloud_api_auth }}"

- name: Call SCORMCloud API
  uri:
    url:                "{{ scormcloud_api_endpoint }}"
    method:             "{{ scormcloud_api_method | default('POST') }}"
    body_format:        "{{ scormcloud_api_body_format | default('json') }}"
    body:               "{{ scormcloud_api_body }}"
    return_content:     yes
    headers:
      Authorization: "Basic {{ scormcloud_api_auth }}"
      X-Experience-API-Version: 1.0.1
      Content-Type: application/json
  register: r_scormcloud_api_call
  # no_log: true

- name: 'DEBUG: Output SCORMCloud Response'
  debug:
    var:          r_scormcloud_api_call
    verbosity:    2
...
